### ISSUE TITLE
Incomplete git repo detection.

### ISSUE THREAD

**Issue by deedoubledub** [ginozab/gitHound#2]
```
/home/d/dwagner/deb/trusty/titanium-studio/titanium-studio/opt/titanium-studio/p
lugins/
No problems with above repo.
```

I should hope so since the above path is not a git repo at all. It does, however, contain two nodes that contain '.git': `com.aptana.git.core_3.0.0.1408413561/` and `com.aptana.git.ui_3.0.3.1407781207.jar`

Your method for detecting git repos will return paths that are not git repos.

**Comment by ginozab** [comment]
I just pushed up new code that should fix this problem
