### ISSUE TITLE
Inelegant handling of bad repo paths

### ISSUE THREAD

**Issue by jwenskovitch** [ginozab/gitHound#3]
```
Would you like to expand the status information of a repo above?
Enter: (yes/no)
yes
Copy and paste a repo from above you would like to expand the status of:
why should i?

*******************************

Invalid working directory path! 
Exiting program...
```

Come up with a better way to handle your user being a jerk aside from exiting the program?

**Comment by ginozab** [comment]
The new code I pushed up will now ask you again if you want to expand a status, after inputing bad repo path. You can decide to try again or exit the program.
